FROM snyk/ubuntu as base

MAINTAINER Snyk Ltd

USER root

RUN apt-get update && apt-get install -y ca-certificates git

USER node
WORKDIR /home/node

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/node_modules/.bin

ADD dockerfiles/.scripts/metadata.json ./
ADD dockerfiles/.scripts/package.json ./
ADD dockerfiles/.scripts/debug.sh ./
ADD dockerfiles/.scripts/install.sh ./

RUN ./install.sh

# Removing debug@0.7.4 (setheader transitive) to satisfy some scanners still reporting this false positive
RUN rm -rf /home/node/node_modules/setheader/node_modules/debug
RUN rm -rf /home/node/node_modules/tough-cookie
RUN npm i -g tough-cookie@4.1.3
RUN mv /home/node/.npm-global/lib/node_modules/tough-cookie /home/node/node_modules

FROM snyk/ubuntu

ENV PATH=$PATH:/home/node/node_modules/.bin

COPY --from=base /home/node/metadata.json /metadata.json
COPY --from=base /home/node/node_modules /home/node/node_modules
COPY --from=base /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

USER root

# Don't run as root
WORKDIR /home/node
USER node

# Generate default accept filter
RUN broker init gitlab

# Support for OpenShift - have to run after init to get accept.json and .env
USER root
RUN chgrp -R 0 /home/node && chmod -R g=u,o= /home/node && chown -R node /home/node
USER node

######################################
# Custom Broker Client configuration #
# Redefine in derived Dockerfile,    #
# or provide as runtime args `-e`    #
######################################

# Your unique broker identifier
# ENV BROKER_TOKEN <broker-token>

# your personal token to your Gitlab server account
# ENV GITLAB_TOKEN <gitlab-token>

# The Gitlab server API URL
# ENV GITLAB your.gitlab.server.hostname

# The port used by the broker client to accept internal connections
# Default value is 7341
# ENV PORT 7341

# The URL of your broker client (including scheme and port)
# This will be used as the webhook payload URL coming in from Gitlab
# ENV BROKER_CLIENT_URL http://<broker.client.hostname>:$PORT

EXPOSE $PORT

CMD ["broker", "--verbose"]
