sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 4
  - 6
before_script:
  - npm run es5ify
  - npm prune
after_success:
  - npm run semantic-release
deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/travis_after_success.sh
  on:
    all_branches: true
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
