ARG BASE_IMAGE=snyk/broker:base

FROM ${BASE_IMAGE}

# Support for OpenShift - have to run after init to get accept.json and .env
USER root
RUN chgrp -R 0 /home/node && chmod -R g=u,o= /home/node && chown -R node /home/node
USER node

EXPOSE $PORT

CMD ["broker", "--verbose"]
