ARG BASE_IMAGE=snyk/broker:base
ARG BROKER_TYPE=github-com


FROM ${BASE_IMAGE} as broker-builder

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/node_modules/.bin

USER root

# install git to resolve snyk-broker branch-based NPM package
RUN apt update && \
    apt install --assume-yes git

ADD dockerfiles/.scripts/debug.sh ./
ADD dockerfiles/.scripts/install.sh ./
ADD dockerfiles/.scripts/metadata.json ./
ADD dockerfiles/.scripts/package.json ./

# clean up broker global installation from base image and install as package dependency
RUN rm -rf /home/node/.npm-global
RUN ./install.sh

# removing non-used (transitive) dependencies to fix vulnerabilities
RUN rm -rf /home/node/node_dmodules/setheader/node_modules/debug
RUN rm -rf /home/node/node_modules/tough-cookie
RUN npm i -g tough-cookie@4.1.3
RUN mv /home/node/.npm-global/lib/node_modules/tough-cookie /home/node/node_modules

FROM ${BASE_IMAGE}

ARG BROKER_TYPE
ENV BROKER_TYPE=${BROKER_TYPE}

ENV PATH=$PATH:/home/node/node_modules/.bin

COPY --from=broker-builder /home/node/metadata.json /metadata.json
COPY --from=broker-builder /home/node/node_modules /home/node/node_modules
COPY config.default.json /home/node/config.default.json
COPY defaultFilters /home/node/defaultFilters

# Support for OpenShift - have to run after init to get accept.json and .env
USER root
RUN chgrp -R 0 /home/node && chmod -R g=u,o= /home/node && chown -R node /home/node
USER node

EXPOSE $PORT

CMD ["/home/node/node_modules/snyk-broker/dist/cli/index.js", "--verbose"]