services:
  broker-client:
    build:
      context: .
      dockerfile: dockerfiles/base/Dockerfile
      target: broker-builder
    working_dir: /home/node/snyk-broker
    command: ["node", "dist/cli/index.js", "client", "--verbose"]
    environment:
      UNIVERSAL_BROKER_ENABLED: "true"
      DEPLOYMENT_ID: "DEPLOYMENT_ID"
      CLIENT_ID: "CLIENT_ID"
      CLIENT_SECRET: "CLIENT_SECRET"
      BROKER_SERVER_URL: "https://broker.snyk.io"
      BROKER_DISPATCHER_BASE_URL: "https://api.snyk.io"
      PORT: "8000"
      METRICS_OTEL_ENDPOINT: "http://otel-collector:4317"
      MY_GH_TOKEN: "TOKEN"
    ports:
      - "8000:8000"
    depends_on:
      - otel-collector
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    configs:
      - source: otel-config
        target: /etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"

configs:
  otel-config:
    content: |
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
      exporters:
        debug:
          verbosity: detailed
      service:
        pipelines:
          metrics:
            receivers: [otlp]
            exporters: [debug]
