ARG BASE_IMAGE=snyk/broker:base-rhel-ubi
ARG BROKER_TYPE=github-com


FROM ${BASE_IMAGE}

ARG BROKER_TYPE
ENV BROKER_TYPE=${BROKER_TYPE}

# Generate default accept filter
RUN broker init $BROKER_TYPE

# Ensure OpenShift compatibility
USER root
RUN chgrp -R 0 /home/snyk && chmod -R 755 /home/snyk
USER snyk

CMD ["broker", "--verbose"]
