FROM snyk/broker:base-rhel-ubi


ARG BROKER_TYPE

# Prepare image entrypoint
COPY ./bin/container-registry-agent/docker-entrypoint.sh /docker-entrypoint.sh
# Generate default accept filter
USER root
RUN broker init container-registry-agent
USER snyk

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["broker", "--verbose"]
