FROM snyk/broker:base-rhel-ubi

ARG BROKER_TYPE

# Prepare image entrypoint
COPY ./bin/container-registry-agent/docker-entrypoint.sh /docker-entrypoint.sh
# Generate default accept filter
USER root
RUN broker init container-registry-agent
USER snyk

ENV NODE_EXTRA_CA_CERTS=${CA_CERT}

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["broker", "--verbose"]
